# Generated by Django 6.0.2 on 2026-02-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "male"), ("Female", "female"), ("Other", "other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
