# Generated by Django 6.0.2 on 2026-02-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="message",
        ),
        migrations.AddField(
            model_name="feedback",
            name="mood",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="feedback",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="stress_level",
            field=models.IntegerField(default=1),
        ),
    ]
