# Generated by Django 6.0.2 on 2026-02-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_sessions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worksession",
            name="notes",
        ),
        migrations.AddField(
            model_name="worksession",
            name="focus_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
